package WeekTwo;

//This program has a variable.

public class variableCase {
	public static void main(String[] args)
	{
		
		
   int value_one;
   String hello;   
   value_one = 8; // be careful with quaotation marks around the variable
   hello = "Hello Class";
   
   
   System.out.print("The value is ");
   System.out.println(value_one);
   //System.out.println("This line is too long and now it has spanned more than one line, 
   // which will cause a syntax error to be generated by the compiler. ");
   System.out.println("These lines are " +
           "are now ok and will not " +
           "cause the error as before.");
   
   System.out.println("The following will be printed " +
           "in a tabbed format: " +
           "\n\tFirst = " + 5 * 6 + ", " +
           "\n\tSecond = " + "(6 + 4)" + "," +
           "\n\tThird = " + 16.7 + "."); 

	}
}